In [1]:
import numpy as np
import pandas as pd
from WindPy import *  
w.start()

Welcome to use Wind Quant API for Python (WindPy)!

COPYRIGHT (C) 2020 WIND INFORMATION CO., LTD. ALL RIGHTS RESERVED.
IN NO CIRCUMSTANCE SHALL WIND BE RESPONSIBLE FOR ANY DAMAGES OR LOSSES CAUSED BY USING WIND QUANT API FOR Python.

.ErrorCode=0
.Data=[OK!]

In [34]:
month_dict = pd.read_excel('data_month.xlsx', sheet_name=1)
month_data = pd.read_excel('data_month.xlsx', sheet_name=0, index_col= 0 )
month_data

,SIP,IVA,IEP,IEE,IEO,IET,NSI,NSP,PRC,OPG,...,NPE,NPOH,NIV,NDT,UOP,UOS,UOO,CCI,CSI,CEI
Date,,,,,,,,,,,,,,,,,,,,,
1992-01-31,NaN,10.9,NaN,NaN,NaN,NaN,NaN,NaN,8114.0,576.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.2,109.7,125.3
1992-02-29,NaN,18.5,NaN,NaN,NaN,NaN,NaN,NaN,14151.0,1129.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.7,110.0,125.3
1992-03-31,NaN,16.8,NaN,NaN,NaN,NaN,NaN,NaN,22816.0,1745.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.5,110.6,125.2
1992-04-30,NaN,15.1,NaN,NaN,NaN,NaN,NaN,NaN,31876.0,2337.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,112.0,111.9,125.0
1992-05-31,NaN,14.3,NaN,NaN,NaN,NaN,NaN,NaN,41608.0,2953.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,114.0,113.5,125.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-30,1.3,6.3,96.6,114362.0,1001708.2,62441.8,596682.4,34021.8,331565.4,62867.4,...,46.6,41.7,45.3,48.7,48.1,49.3,48.5,87.2,86.5,88.4
2022-10-31,0.1,5.0,100.2,127458.0,1117838.7,69768.2,664199.6,36196.9,368539.7,69576.1,...,46.1,43.1,45.7,48.3,49.2,48.4,48.3,86.8,87.1,86.3
2022-11-30,-1.9,2.2,96.6,140467.0,1239568.9,77179.6,730010.5,38595.9,409407.9,76285.8,...,45.5,43.2,45.6,45.0,49.4,46.7,47.0,85.5,86.3,84.2
2022-12-31,-0.8,1.3,96.7,153427.0,1379098.4,84038.5,825967.4,43148.2,449583.9,83886.3,...,42.9,43.0,45.4,40.4,49.0,48.0,48.3,88.3,87.1,90.1
2023-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.7,43.3,47.7,49.7,49.2,52.9,51.1,NaN,NaN,NaN

In [39]:
month_dict['']

,Code,Factor,Factor_CN,Unit,ID,begin_time,Source,Release Batch
0,SIP,Service industry production index: year-on-year,服务业生产指数:当月同比,%,M5767203,2016-12,National Bureau of Statistics,8
1,IVA,Industrial value added: year-on-year,工业增加值:当月同比,%,M0000545,1990-01,National Bureau of Statistics,8
2,IEP,Industrial enterprises: Production and sales r...,工业企业:产销率:累计值,%,M0041768,2001-01,National Bureau of Statistics,8
3,IEE,Industrial Enterprises: Export Delivery Value:...,工业企业:出口交货值:累计值,100M Yuan,M0041769,2002-01,National Bureau of Statistics,8
4,IEO,Industrial enterprises: Operating income: Cumu...,工业企业:营业收入:累计值,100M Yuan,M5767811,2017-02,National Bureau of Statistics,13
...,...,...,...,...,...,...,...,...
76,UOS,Unofficial China Services PMI: Business Activi...,非官方中国服务业PMI:经营活动指数,NaN,M0061603,2008-10,According to the news,2
77,UOO,Unofficial China Composite PMI:Output Index,非官方中国综合PMI:产出指数,NaN,M0290204,2015-01,According to the news,2
78,CCI,Consumer Confidence Index,消费者信心指数(月),NaN,M0012303,1991-01,National Bureau of Statistics,3
79,CSI,Consumer Satisfaction Index,消费者满意指数(月),NaN,M0012304,1991-01,National Bureau of Statistics,3
80,CEI,Consumer Expectation Index,消费者预期指数(月),NaN,M0012305,1991-01,National Bureau of Statistics,3

In [7]:
pd.read_excel('all_data_month.xlsx', sheet_name=1)['ID']

,Code,Factor,Factor_CN,Unit,ID,begin_time,来源,更新时间
0,SIP,Service industry production index: year-on-year,服务业生产指数:当月同比,%,M5767203,2016-12,国家统计局,'2023-01-17
1,IVA,Industrial value added: year-on-year,工业增加值:当月同比,%,M0000545,1990-01,国家统计局,'2023-01-17
2,IEP,Industrial enterprises: Production and sales r...,工业企业:产销率:累计值,%,M0041768,2001-01,国家统计局,'2023-01-17
3,IEE,Industrial Enterprises: Export Delivery Value:...,工业企业:出口交货值:累计值,亿元,M0041769,2002-01,国家统计局,'2023-01-17
4,IEO,Industrial enterprises: Operating income: Cumu...,工业企业:营业收入:累计值,亿元,M5767811,2017-02,国家统计局,'2023-01-31
...,...,...,...,...,...,...,...,...
77,UOS,Unofficial China Services PMI: Business Activi...,非官方中国服务业PMI:经营活动指数,%,M0061603,2008-10,根据新闻整理,'2023-02-03
78,UOO,Unofficial China Composite PMI:Output Index,非官方中国综合PMI:产出指数,%,M0290204,2015-01,根据新闻整理,'2023-02-03
79,CCI,Consumer Confidence Index,消费者信心指数(月),NaN,M0012303,1991-01,国家统计局,'2023-02-06
80,CSI,Consumer Satisfaction Index,消费者满意指数(月),NaN,M0012304,1991-01,国家统计局,'2023-02-06
81,CEI,Consumer Expectation Index,消费者预期指数(月),NaN,M0012305,1991-01,国家统计局,'2023-02-06

In [38]:
w.edb(','.join(month_dict['ID']), month_data.index[-3],datetime.date(datetime.now()), 'Fill=Previous',   usedf=True )[1]

,M5767203,M0000545,M0041768,M0041769,M5767811,M0000556,M0049801,M0049802,S0026991,S0027014,...,M5207830,M0088875,M0088876,M0088877,M0000138,M0061603,M0290204,M0012303,M0012304,M0012305
2022-11-30,-1.9,2.2,96.6,140467.0,1239568.9,77179.6,730010.5,38595.9,409407.9,76285.8,...,45.5,43.2,45.6,45.0,49.4,46.7,47.0,85.5,86.3,84.2
2022-12-31,-0.8,1.3,96.7,153427.0,1379098.4,84038.5,825967.4,43148.2,449583.9,83886.3,...,42.9,43.0,45.4,40.4,49.0,48.0,48.3,88.3,87.1,90.1
2023-01-31,-0.8,1.3,96.7,153427.0,1379098.4,84038.5,825967.4,43148.2,449583.9,83886.3,...,46.7,43.3,47.7,49.7,49.2,52.9,51.1,88.3,87.1,90.1
2023-02-28,-0.8,1.3,96.7,153427.0,1379098.4,84038.5,825967.4,43148.2,449583.9,83886.3,...,50.2,50.3,48.2,55.2,51.6,55.0,54.2,88.3,87.1,90.1

In [36]:
','.join(month_dict['ID'])

'M5767203,M0000545,M0041768,M0041769,M5767811,M0000556,M0049801,M0049802,S0026991,S0027014,M0000612,M0085932,M0001227,M0000604,M0000606,M0000608,C5756400,V0989584,M0009870,M0000272,S0029656,M0001439,M0001483,M0001385,M0009970,M0009941,M5542229,M0010049,M5207845,M5207847,M5405536,M5525763,M5525764,M5525766,M5525767,M5525769,M6179510,M0024243,M0041746,M0341969,M0341965,M0041688,M0041697,M0041693,M0046168,M0046170,M0046166,M0096879,M0096887,M5480389,M5650805,M0017126,M0017127,M0017128,M0017129,M0017130,M0017131,M0017132,M0017133,M5766711,M0017134,M0017135,M0017136,M0017137,M5207790,M0048236,M0048237,M0048238,M0048239,M0048240,M0068606,M5207830,M0088875,M0088876,M0088877,M0000138,M0061603,M0290204,M0012303,M0012304,M0012305'